{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "deefa902-8c59-4ced-a4e8-24a1f6076774",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: invoice2data in .\\anaconda3\\Lib\\site-packages (0.5.0)\n",
      "Requirement already satisfied: click>=8.0.1 in .\\anaconda3\\Lib\\site-packages (from invoice2data) (8.1.8)\n",
      "Requirement already satisfied: dateparser>=1.2.0 in .\\anaconda3\\Lib\\site-packages (from invoice2data) (1.4.0)\n",
      "Requirement already satisfied: PyYAML>=6.0 in .\\anaconda3\\Lib\\site-packages (from invoice2data) (6.0.2)\n",
      "Requirement already satisfied: regex>=2025.2.10 in .\\anaconda3\\Lib\\site-packages (from invoice2data) (2026.5.9)\n",
      "Requirement already satisfied: colorama in .\\anaconda3\\Lib\\site-packages (from click>=8.0.1->invoice2data) (0.4.6)\n",
      "Requirement already satisfied: python-dateutil>=2.7.0 in .\\anaconda3\\Lib\\site-packages (from dateparser>=1.2.0->invoice2data) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2024.2 in .\\anaconda3\\Lib\\site-packages (from dateparser>=1.2.0->invoice2data) (2026.2)\n",
      "Requirement already satisfied: tzlocal>=0.2 in .\\anaconda3\\Lib\\site-packages (from dateparser>=1.2.0->invoice2data) (5.3.1)\n",
      "Requirement already satisfied: six>=1.5 in .\\anaconda3\\Lib\\site-packages (from python-dateutil>=2.7.0->dateparser>=1.2.0->invoice2data) (1.17.0)\n",
      "Requirement already satisfied: tzdata in .\\anaconda3\\Lib\\site-packages (from tzlocal>=0.2->dateparser>=1.2.0->invoice2data) (2025.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install invoice2data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "26a158cd-f2ce-4fe3-aded-6b0939adfb77",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pip in .\\anaconda3\\Lib\\site-packages (26.1.2)Note: you may need to restart the kernel to use updated packages.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "pip install --upgrade pip"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "af1f7d34-8f22-4be8-b11f-656b75fa2a32",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: invoice2data in .\\anaconda3\\Lib\\site-packages (0.5.0)\n",
      "Requirement already satisfied: pandas in .\\anaconda3\\Lib\\site-packages (2.2.3)\n",
      "Requirement already satisfied: openpyxl in .\\anaconda3\\Lib\\site-packages (3.1.5)\n",
      "Collecting pdftotext\n",
      "  Downloading pdftotext-3.0.0.tar.gz (113 kB)\n",
      "  Installing build dependencies: started\n",
      "  Installing build dependencies: finished with status 'done'\n",
      "  Getting requirements to build wheel: started\n",
      "  Getting requirements to build wheel: finished with status 'done'\n",
      "  Preparing metadata (pyproject.toml): started\n",
      "  Preparing metadata (pyproject.toml): finished with status 'done'\n",
      "Requirement already satisfied: click>=8.0.1 in .\\anaconda3\\Lib\\site-packages (from invoice2data) (8.1.8)\n",
      "Requirement already satisfied: dateparser>=1.2.0 in .\\anaconda3\\Lib\\site-packages (from invoice2data) (1.4.0)\n",
      "Requirement already satisfied: PyYAML>=6.0 in .\\anaconda3\\Lib\\site-packages (from invoice2data) (6.0.2)\n",
      "Requirement already satisfied: regex>=2025.2.10 in .\\anaconda3\\Lib\\site-packages (from invoice2data) (2026.5.9)\n",
      "Requirement already satisfied: numpy>=1.26.0 in .\\anaconda3\\Lib\\site-packages (from pandas) (2.1.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in .\\anaconda3\\Lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in .\\anaconda3\\Lib\\site-packages (from pandas) (2026.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in .\\anaconda3\\Lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: et-xmlfile in .\\anaconda3\\Lib\\site-packages (from openpyxl) (1.1.0)\n",
      "Requirement already satisfied: colorama in .\\anaconda3\\Lib\\site-packages (from click>=8.0.1->invoice2data) (0.4.6)\n",
      "Requirement already satisfied: tzlocal>=0.2 in .\\anaconda3\\Lib\\site-packages (from dateparser>=1.2.0->invoice2data) (5.3.1)\n",
      "Requirement already satisfied: six>=1.5 in .\\anaconda3\\Lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Building wheels for collected packages: pdftotext\n",
      "  Building wheel for pdftotext (pyproject.toml): started\n",
      "  Building wheel for pdftotext (pyproject.toml): finished with status 'error'\n",
      "Failed to build pdftotext\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  Building wheel for pdftotext (pyproject.toml) did not run successfully.\n",
      "  exit code: 1\n",
      "  \n",
      "  [11 lines of output]\n",
      "  <string>:54: SyntaxWarning: invalid escape sequence '\\i'\n",
      "  <string>:55: SyntaxWarning: invalid escape sequence '\\l'\n",
      "  WARNING: pkg-config not found--guessing at poppler version.\n",
      "           If the build fails, install pkg-config and try again.\n",
      "  WARNING: pkg-config not found--guessing at poppler version.\n",
      "           If the build fails, install pkg-config and try again.\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_ext\n",
      "  building 'pdftotext' extension\n",
      "  error: Microsoft Visual C++ 14.0 or greater is required. Get it with \"Microsoft C++ Build Tools\": https://visualstudio.microsoft.com/visual-cpp-build-tools/\n",
      "  [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for pdftotext\n",
      "error: failed-wheel-build-for-install\n",
      "\n",
      "Failed to build installable wheels for some pyproject.toml based projects\n",
      "\n",
      "pdftotext\n"
     ]
    }
   ],
   "source": [
    "pip install invoice2data pandas openpyxl "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5f7aad6c-697b-49fb-b8ab-55f2dec50966",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "============================================================\n",
      "PDF INVOICE EXTRACTION STARTED\n",
      "============================================================\n",
      "\n",
      "Found 1 PDF file(s)\n",
      "\n",
      "[SUCCESS] wordpress-pdf-invoice-plugin-sample.pdf\n",
      "\n",
      "============================================================\n",
      "PROCESSING SUMMARY\n",
      "============================================================\n",
      "Total Files : 1\n",
      "Successful  : 1\n",
      "Failed      : 0\n",
      "\n",
      "Excel Saved:\n",
      "E:\\PDF TO EXCEL\\invoice\\invoice_summary.xlsx\n",
      "\n",
      "============================================================\n",
      "PROCESS COMPLETED\n",
      "============================================================\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import re\n",
    "from datetime import datetime\n",
    "\n",
    "import pandas as pd\n",
    "import pdfplumber\n",
    "from openpyxl import load_workbook\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# CONFIGURATION\n",
    "# =====================================================\n",
    "\n",
    "INVOICE_FOLDER = r\"E:\\PDF TO EXCEL\\invoice\"\n",
    "OUTPUT_FILE = r\"E:\\PDF TO EXCEL\\invoice\\invoice_summary.xlsx\"\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# HELPER FUNCTIONS\n",
    "# =====================================================\n",
    "\n",
    "def extract_text_from_pdf(pdf_path):\n",
    "    \"\"\"\n",
    "    Extract text from all pages of a PDF.\n",
    "    \"\"\"\n",
    "\n",
    "    full_text = \"\"\n",
    "\n",
    "    with pdfplumber.open(pdf_path) as pdf:\n",
    "        for page in pdf.pages:\n",
    "            full_text += (page.extract_text() or \"\") + \"\\n\"\n",
    "\n",
    "    return full_text\n",
    "\n",
    "\n",
    "def extract_match(pattern, text):\n",
    "    \"\"\"\n",
    "    Extract first regex match.\n",
    "    \"\"\"\n",
    "\n",
    "    match = re.search(pattern, text, re.I | re.MULTILINE)\n",
    "\n",
    "    if match:\n",
    "        return match.group(1).strip()\n",
    "\n",
    "    return None\n",
    "\n",
    "\n",
    "def safe_float(value):\n",
    "    \"\"\"\n",
    "    Convert string number to float safely.\n",
    "    \"\"\"\n",
    "\n",
    "    if not value:\n",
    "        return None\n",
    "\n",
    "    try:\n",
    "        value = (\n",
    "            str(value)\n",
    "            .replace(\"$\", \"\")\n",
    "            .replace(\"₹\", \"\")\n",
    "            .replace(\",\", \"\")\n",
    "            .strip()\n",
    "        )\n",
    "\n",
    "        return float(value)\n",
    "\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "\n",
    "def auto_fit_excel_columns(excel_path):\n",
    "    \"\"\"\n",
    "    Auto adjust Excel column widths.\n",
    "    \"\"\"\n",
    "\n",
    "    wb = load_workbook(excel_path)\n",
    "\n",
    "    ws = wb.active\n",
    "\n",
    "    for column in ws.columns:\n",
    "\n",
    "        max_length = 0\n",
    "\n",
    "        column_letter = column[0].column_letter\n",
    "\n",
    "        for cell in column:\n",
    "\n",
    "            try:\n",
    "                cell_length = len(str(cell.value))\n",
    "\n",
    "                if cell_length > max_length:\n",
    "                    max_length = cell_length\n",
    "\n",
    "            except:\n",
    "                pass\n",
    "\n",
    "        ws.column_dimensions[column_letter].width = max_length + 3\n",
    "\n",
    "    wb.save(excel_path)\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# MAIN PROCESS\n",
    "# =====================================================\n",
    "\n",
    "records = []\n",
    "\n",
    "pdf_files = [\n",
    "    file\n",
    "    for file in os.listdir(INVOICE_FOLDER)\n",
    "    if file.lower().endswith(\".pdf\")\n",
    "]\n",
    "\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"PDF INVOICE EXTRACTION STARTED\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "print(f\"\\nFound {len(pdf_files)} PDF file(s)\\n\")\n",
    "\n",
    "for file in pdf_files:\n",
    "\n",
    "    pdf_path = os.path.join(INVOICE_FOLDER, file)\n",
    "\n",
    "    try:\n",
    "\n",
    "        full_text = extract_text_from_pdf(pdf_path)\n",
    "\n",
    "        # -------------------------------------------------\n",
    "        # Extract Fields\n",
    "        # -------------------------------------------------\n",
    "\n",
    "        invoice_no = extract_match(\n",
    "            r\"Invoice\\s*(?:No|Number)\\s*[:#]?\\s*([A-Z0-9\\-]+)\",\n",
    "            full_text\n",
    "        )\n",
    "\n",
    "        order_no = extract_match(\n",
    "            r\"Order\\s*(?:No|Number|#)\\s*[:#]?\\s*([A-Z0-9\\-]+)\",\n",
    "            full_text\n",
    "        )\n",
    "\n",
    "        invoice_date = extract_match(\n",
    "            r\"Invoice Date\\s*([A-Za-z]+\\s+\\d{1,2},\\s+\\d{4})\",\n",
    "            full_text\n",
    "        )\n",
    "\n",
    "        due_date = extract_match(\n",
    "            r\"Due Date\\s*([A-Za-z]+\\s+\\d{1,2},\\s+\\d{4})\",\n",
    "            full_text\n",
    "        )\n",
    "\n",
    "        customer = extract_match(\n",
    "            r\"To:\\s*\\n([^\\n]+)\",\n",
    "            full_text\n",
    "        )\n",
    "\n",
    "        subtotal = safe_float(\n",
    "            extract_match(\n",
    "                r\"Sub\\s*Total\\s*\\$?\\s*([\\d,]+\\.\\d+)\",\n",
    "                full_text\n",
    "            )\n",
    "        )\n",
    "\n",
    "        tax = safe_float(\n",
    "            extract_match(\n",
    "                r\"Tax\\s*\\$?\\s*([\\d,]+\\.\\d+)\",\n",
    "                full_text\n",
    "            )\n",
    "        )\n",
    "\n",
    "        total = safe_float(\n",
    "            extract_match(\n",
    "                r\"Total Due\\s*\\$?\\s*([\\d,]+\\.\\d+)\",\n",
    "                full_text\n",
    "            )\n",
    "        )\n",
    "\n",
    "        records.append({\n",
    "            \"File Name\": file,\n",
    "            \"Invoice No\": invoice_no,\n",
    "            \"Order No\": order_no,\n",
    "            \"Invoice Date\": invoice_date,\n",
    "            \"Due Date\": due_date,\n",
    "            \"Customer\": customer,\n",
    "            \"Subtotal\": subtotal,\n",
    "            \"Tax\": tax,\n",
    "            \"Total\": total,\n",
    "            \"Status\": \"SUCCESS\",\n",
    "            \"Processed On\": datetime.now().strftime(\n",
    "                \"%Y-%m-%d %H:%M:%S\"\n",
    "            )\n",
    "        })\n",
    "\n",
    "        print(f\"[SUCCESS] {file}\")\n",
    "\n",
    "    except Exception as e:\n",
    "\n",
    "        print(f\"[FAILED ] {file}\")\n",
    "        print(f\"Reason   : {e}\")\n",
    "\n",
    "        records.append({\n",
    "            \"File Name\": file,\n",
    "            \"Invoice No\": None,\n",
    "            \"Order No\": None,\n",
    "            \"Invoice Date\": None,\n",
    "            \"Due Date\": None,\n",
    "            \"Customer\": None,\n",
    "            \"Subtotal\": None,\n",
    "            \"Tax\": None,\n",
    "            \"Total\": None,\n",
    "            \"Status\": \"FAILED\",\n",
    "            \"Processed On\": datetime.now().strftime(\n",
    "                \"%Y-%m-%d %H:%M:%S\"\n",
    "            )\n",
    "        })\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# BUILD DATAFRAME\n",
    "# =====================================================\n",
    "\n",
    "df = pd.DataFrame(records)\n",
    "\n",
    "column_order = [\n",
    "    \"File Name\",\n",
    "    \"Invoice No\",\n",
    "    \"Order No\",\n",
    "    \"Invoice Date\",\n",
    "    \"Due Date\",\n",
    "    \"Customer\",\n",
    "    \"Subtotal\",\n",
    "    \"Tax\",\n",
    "    \"Total\",\n",
    "    \"Status\",\n",
    "    \"Processed On\"\n",
    "]\n",
    "\n",
    "df = df[column_order]\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# SAVE EXCEL\n",
    "# =====================================================\n",
    "\n",
    "os.makedirs(\n",
    "    os.path.dirname(OUTPUT_FILE),\n",
    "    exist_ok=True\n",
    ")\n",
    "\n",
    "df.to_excel(\n",
    "    OUTPUT_FILE,\n",
    "    index=False\n",
    ")\n",
    "\n",
    "auto_fit_excel_columns(OUTPUT_FILE)\n",
    "\n",
    "\n",
    "# =====================================================\n",
    "# SUMMARY\n",
    "# =====================================================\n",
    "\n",
    "total_files = len(df)\n",
    "\n",
    "successful = len(\n",
    "    df[df[\"Status\"] == \"SUCCESS\"]\n",
    ")\n",
    "\n",
    "failed = len(\n",
    "    df[df[\"Status\"] == \"FAILED\"]\n",
    ")\n",
    "\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"PROCESSING SUMMARY\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "print(f\"Total Files : {total_files}\")\n",
    "print(f\"Successful  : {successful}\")\n",
    "print(f\"Failed      : {failed}\")\n",
    "\n",
    "print(\"\\nExcel Saved:\")\n",
    "print(OUTPUT_FILE)\n",
    "\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"PROCESS COMPLETED\")\n",
    "print(\"=\" * 60)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "32c609d9-8ffa-477e-a130-9916b78da59c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
